### ISSUE TITLE
Console error while using resizeHandler

### ISSUE THREAD

**Issue by JananiGunasekaran** [cerner/terra-graphs#10]
**What part of Carbon does this bug correlate to?**
General graph logic:

* [x]  Graph attributes (axes, legends, regions...etc.)
* [ ]  Other (please specify): 

Specific graph logic:

* [ ]  Bar graph
* [ ]  Bubble graph
* [ ]  Gantt chart
* [x]  Line graph
* [x]  Paired result
* [ ]  Pie chart
* [ ]  Scatter plot
* [ ]  Timeline

**Describe the bug**
There is a console error in our advanced-graphing application when we use resizeHandler().

**Expected behavior**
Graphs should be resized without any console error in the browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/60426528/98098449-5beae780-1eb4-11eb-9b6b-ad4bbee9ca72.png)

**Comment by AshishMotanamGurunadham** [comment]
@JananiGunasekaran as we moved to terra-graphs,  please raise PR for this issue here.

**Comment by JananiGunasekaran** [comment]
I have raised PR in terra-graphs https://github.com/cerner/terra-graphs/pull/17. Please review.
