### ISSUE TITLE
Bug: Reflow crashes when showLegend=false

### ISSUE THREAD

**Issue by sdadn** [cerner/terra-graphs#103]
# Bug Report

## Description

When `showLegend` is set to `false`, reflow throws an error and crashes. This is seemingly caused by reflow trying to update the legend when there is none.

### Graphs affected

* [ ]  Bar graph
* [ ]  Bubble graph
* [ ]  Gantt chart
* [ ]  Line graph
* [ ]  Paired result
* [ ]  Pie chart
* [ ]  Scatter plot
* [x]  Timeline

## Steps to Reproduce

1. Create a graph
2. Set `showLegend = false` in the graph config
3. Call the reflow method

## Link to CodeSandbox
Use [this](https://codesandbox.io/s/keen-thunder-nh5gk?file=/src/data.js) template to reproduce the behavior.

## Possible Solution

Use a conditional statement to bypass the update legend logic if there is no legend.

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by gerard-isdell** [comment]
Hi @sdadn  Do you know when the next version of carbon-graphs is due to be released?

**Comment by mjhenkes** [comment]
@gerard-isdell we release on Tuesday, if there are unreleased changes in main. So we'll release today!

**Comment by gerard-isdell** [comment]
Great  - thanks!
