### ISSUE TITLE
Spike: Investigate the design for handling panning components in terra-graphs

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-graphs#116]
# Feature Request

## Description

As a developer, I want to land on a clear design for how we want to handle panning components in terra-graphs

So that we can proceed with the actual work to move that logic to terra-graphs

We'll know we're done when we have a clear idea on how to proceed and additional tasks are logged with information on what needs to be done

**Comment by sdadn** [comment]
Concluded spike by establishing a rough design of incorporating panning in the react components. The design will use React Effects. The next part of this story has moved to #131 to start with a line component.
