### ISSUE TITLE
Spike: Developing an API for line graph

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-graphs#129]
# Feature Request

## Description

As a developer of terra, I want to develop a new API for line graph

So that I can improve upon the clarity and consistency from the existing API and ensure that it will support things like accessibility.

We'll know we're done when we have a proposed API documented

**Comment by sdadn** [comment]
Spike conclusion: 
Concluded to design a react component for each graph type, with a  common JS API that provides the common functionality.

Next Steps:
- Address accessibility design questions
- Prop design
- Core API design
