### ISSUE TITLE
Spike: Investigate "Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined"

### ISSUE THREAD

**Issue by sdadn** [cerner/terra-graphs#130]
As an engineer, I would like investigate the error below:

From: @dp21g
I'm getting an error in our branch when importing the new changes from the release.
``` 
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at n.e.generate (carbon-graphs.js?db72:1)
    at new n (carbon-graphs.js?db72:1)
    at Object.timeline (carbon-graphs.js?db72:1)
    at EventTimeline.create (EventTimeline.jsx?04d5:279)
    at EventTimeline.componentDidMount (EventTimeline.jsx?04d5:121)
```
this happens in our master and my new branch for the reflow changes.
https://github.cerner.com/UKDevelopment-ClinicalDev/stella-timeline/tree/eventlines-misaligned-when-resized

_Originally posted by @dp21g in https://github.com/cerner/terra-graphs/issues/118#issuecomment-839954197_

### Motivation
To determine the root cause of the problem.

**Comment by sdadn** [comment]
@dp21g Are you still getting the error? If so, can you create a sandbox that reproduces the error?

**Comment by dp21g** [comment]
so we managed to resolve it by avoiding the hard coded padding we added to our dev site examples.
https://github.cerner.com/stella/stella-timeline/pull/397
None of our consumers have reported issues and our wdio tests were fine so we can close this for now.
