### ISSUE TITLE
The target element (goal\region) overlays the ability to click on the carbon-graphs data.

### ISSUE THREAD

**Issue by O-Oleh** [cerner/terra-graphs#136]
# Bug Report

## Description
If we have a target element on the carbon-graphs it overlays the ability to click on the data and it doesn't allow to call popover with some data from the graphs.

### Graphs affected

* [x]  Bar graph
* [x]  Bubble graph
* [x]  Gantt chart
* [x]  Line graph
* [x]  Paired result
* [x]  Pie chart
* [x]  Scatter plot
* [ ]  Timeline

## Steps to Reproduce
1. Add `regions` property for the `data` array. 
2. One of the values has to have `x` value like one of the region's values.

## Link to CodeSandbox
[codesandbox example](https://codesandbox.io/s/infallible-fermi-5110h?file=/src/data.js)

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/10379680/119684954-9b2b5680-be4d-11eb-8174-770aa88d52aa.png)
![image](https://user-images.githubusercontent.com/10379680/119685061-b5fdcb00-be4d-11eb-8334-bb19ed140695.png)

## Expected Behavior
User can click on the graph data with target element.

## Possible Solution
Change rendering order for the `carbon-region`, element under the number 2 has to have position before element under the number 1.
![image](https://user-images.githubusercontent.com/10379680/119688911-16423c00-be51-11eb-8d5d-a4e2567d7dee.png)

## Environment
N/A

## @ Mentions

**Comment by ryanthemanuel** [comment]
This is an issue and will be fixed by #149 149
