### ISSUE TITLE
UI glitch while rendering graphs having Y2 axis

### ISSUE THREAD

**Issue by shabreesh-1998** [cerner/terra-graphs#192]
# Bug Report

## Description
We are observing a behavior with the axes labels, where while re-rendering the axes labels shows up at a particular spot and goes off. This we are observing in this graph as it has a Y2 axis (not observing this in graphs with only 1 Y-axis). I am attaching a video evidence as well as a snapshot for reference.

### Graphs affected

* [ ]  Bar graph
* [ ]  Bubble graph
* [ ]  Gantt chart
* [x]  Line graph
* [ ]  Paired result
* [ ]  Pie chart
* [ ]  Scatter plot
* [ ]  Timeline

## Steps to Reproduce

1. This happens with any graph having a Y2 axis

## Link to CodeSandbox
N/A
## Additional Context / Screenshots
![MicrosoftTeams-image](https://user-images.githubusercontent.com/60382279/126292148-ff966981-1838-4fbd-a5a3-f702d09087c1.png)

## Expected Behavior
We are not supposed to see the legends rendering as shown in the screenshot.

## Environment

* Component Name and Version: (partogram-js)[https://github.cerner.com/aeon-womenshealth/partogram-js]
* Browser Name and Version: IE 10/11
* Node/npm Version: Node 10
* Webpack Version:
* Operating System and version (desktop or mobile):

## @ Mentions
@AshishMotanamGurunadham

**Comment by AshishMotanamGurunadham** [comment]
@shabreesh-1998 can you please add a [code sandbox](https://codesandbox.io/s/keen-thunder-nh5gk?file=/src/data.js) example for this issue and can you also add video evidence you mentioned in the description.

**Comment by shabreesh-1998** [comment]
> @shabreesh-1998 can you please add a [code sandbox](https://codesandbox.io/s/keen-thunder-nh5gk?file=/src/data.js) example for this issue and can you also add video evidence you mentioned in the description.

Here is the link to video: https://cernerprod-my.sharepoint.com/:v:/g/personal/sn078210_cerner_net/EbvT9E9WMAFGtvAXga62CA0Bvo-XbHw2az7jsB06pHs_2g?e=U1cnBZ

**Comment by AshishMotanamGurunadham** [comment]
Looks like the transform points are not set to the axis shape element initially, that is the reason why we are seeing this issue and this will be fixed in coming iteration.
