### ISSUE TITLE
Connecting line does not go away for paired results when toggled off in IE

### ISSUE THREAD

**Issue by RamGaikwad12** [cerner/terra-graphs#20]
# Bug Report

## Description
Connecting line does not go away for paired results when toggled off in IE
The line would disappear when either High or Low is toggled off in Chrome but not working as expected in IE

### Graphs affected

* [ ]  Bar graph
* [ ]  Bubble graph
* [ ]  Gantt chart
* [ ]  Line graph
* [x]  Paired result
* [ ]  Pie chart
* [ ]  Scatter plot
* [ ]  Timeline

## Steps to Reproduce
1. Open paired results.
2. Toggle off either High or Low legend.
3. The connecting line does not disappear.

## Additional Context / Screenshots
![Carbon](https://user-images.githubusercontent.com/57666962/99764906-05241580-2b24-11eb-8a0b-ddf85329fb82.png)

## Expected Behavior
The connecting line should disappear when either High or Low legend is toggled off.

## Environment

* Component Name and Version:
* Browser Name and Version: Internet Explorer 11
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by NarasimhaShenoi** [comment]
@mraplumb / @sdadn Can you please provide an ETA for this issue.

**Comment by joelsamthomas** [comment]
@AshishMotanamGurunadham  any updates on the progress and on the ETA  of this issue. We have few Jiras waiting on this one

**Comment by AshishMotanamGurunadham** [comment]
@joelsamthomas Sorry for the delay, most probably I will start working on it today and we will try to release this as soon as we can.

**Comment by joelsamthomas** [comment]
@AshishMotanamGurunadham  Thank you for the update. Any ETA on this one?

**Comment by AshishMotanamGurunadham** [comment]
@joelsamthomas Actually, we got some priority issues to work on in between this week. so PR will get ready for this issue around next week and we will release it as soon as we can.

**Comment by ji2307** [comment]
@AshishMotanamGurunadham - Are you planning on picking this back up this week?

**Comment by mraplumb** [comment]
@ji2307 a PR was just posted with the correction for this issue.
