### ISSUE TITLE
Update date format string for locales as per internationalization Standards.

### ISSUE THREAD

**Issue by AshishMotanamGurunadham** [cerner/terra-graphs#219]
# Story

## Description

As a <consumer/designer/user of graphs> I would like to update the date format(date month) for locales like Swedish (SV), French (fr), or Dutch (NL) to meet internationalization standards.

## Motivation

So that date format on the axis will be displayed as per internationalized standatards.

## Definition of Done

We'll know we're done when we are able to display the correct date format on the axis for locales like Swedish (SV), French (fr) or Dutch (NL).

**Comment by ryanthemanuel** [comment]
Closing this as we're tracking this internally.
