### ISSUE TITLE
Y-axis range getting changed during reflow

### ISSUE THREAD

**Issue by NarasimhaShenoi** [cerner/terra-graphs#65]
# Bug Report

## Description

Y-axis range is getting updated while reflow for a graph that has autocalibration set to true. This is happening because we are updating [axisRange](https://github.com/cerner/terra-graphs/blob/main/packages/carbon-graphs/src/js/controls/Graph/Graph.js#L461) for each dataset with reflow. 

## Steps to Reproduce

1. Create a graph with 2 data series and set the autocalibration to true
2. Update the y-axis value via the reflow method
3. Y-axis range will get changed each time the reflow method is getting called, even though the data remains the same.

## Additional Context / Screenshots

Before Panning:
<img width="1474" alt="Screenshot 2021-01-20 at 10 14 35 PM" src="https://user-images.githubusercontent.com/53594676/105206910-e4505e80-5b6c-11eb-9b52-cc762650f4a3.png">
After Panning, the y-axis limit gets updated each time we click on the panning button:
<img width="1473" alt="Screenshot 2021-01-20 at 10 17 21 PM" src="https://user-images.githubusercontent.com/53594676/105207223-46a95f00-5b6d-11eb-9c3c-d3ad5aea36a6.png">
<img width="1472" alt="Screenshot 2021-01-20 at 10 17 46 PM" src="https://user-images.githubusercontent.com/53594676/105207279-54f77b00-5b6d-11eb-89a4-c5fdc4e72f16.png">
<img width="1473" alt="Screenshot 2021-01-20 at 10 18 00 PM" src="https://user-images.githubusercontent.com/53594676/105207301-5e80e300-5b6d-11eb-9ed6-59908e6a9dd8.png">

## Expected Behavior

y-axis range should not get updated when the data is same

**Comment by AshishMotanamGurunadham** [comment]
@NarasimhaShenoi can you please add a sandbox example?

**Comment by NarasimhaShenoi** [comment]
@AshishMotanamGurunadham I am able to reproduce the issue in terra-graphs as well. I am adding the [sandbox](https://codesandbox.io/s/long-snowflake-vjf2f?file=/src/data.js) example of the same.

**Comment by NarasimhaShenoi** [comment]
@AshishMotanamGurunadham Can you please provide an ETA for this issue?

**Comment by AshishMotanamGurunadham** [comment]
> @AshishMotanamGurunadham Can you please provide an ETA for this issue

@NarasimhaShenoi we will try to release it by next week.
