### ISSUE TITLE
Define a region per value - scatter plot 

### ISSUE THREAD

**Issue by erinplourde** [cerner/terra-graphs#70]
Provide a feature for consumers to provide region independently per value in the graph. This issue already exists for line graphs - the same should be done for scatter plots. 

Line Graph PR: https://github.com/cerner/carbon-graphs/pull/258

**Comment by mraplumb** [comment]
The use of regions per value necessitates the use of linear data which is not the basis of a scatter plot.  A line graph has been recommended for this use case which supports these types of regions.
