### ISSUE TITLE
Graph getting shifted towards right during reflow.

### ISSUE THREAD

**Issue by NarasimhaShenoi** [cerner/terra-graphs#79]
# Bug Report

## Description

When we create a graph with space as a y-axis label and try to update the y-axis label with reflow, the graph is shifting the position to the right. 

## Steps to Reproduce

1. Create a graph having only y-axis with space as y-axis label
2. Try to update the y-axis label with the reflow method
3. graph gets shifted towards the right to accommodate the y-axis label.

Sandbox example [here](https://codesandbox.io/s/frosty-ganguly-lxu1c?file=/src/graph.js)

## Expected Behavior

when y-axis label is updated, the graph should not get shifted.

**Comment by sdadn** [comment]
HI Narasimha. This is not really a bug, just a choice based on the design of Carbon. When a label is not rendered, then the label container has 0 width. When the label text is updated, the label container width is also updated to render the label. The graph container is moved to the right to accommodate it, which was the solution to the label issue. 

![slice1](https://user-images.githubusercontent.com/38024451/109564726-15467c00-7aa7-11eb-9faa-07e2d2c1b236.png)

**Comment by NarasimhaShenoi** [comment]
Hey @sdadn , We have our [application](https://pages.github.cerner.com/critical-care/critical-care-js/tests/critical-care-js/critical-care) where graph and other components align with the timeline. But with this design, when we pass space as the label, the graph will no longer align with the timeline and other components. I have attached the screenshot of how the graph does not align with the timeline and other graph components when we pass space as a label.
<img width="1473" alt="Screenshot 2021-03-02 at 3 18 12 PM" src="https://user-images.githubusercontent.com/53594676/109630081-826f1580-7b6a-11eb-9bed-ff0ef1b5306a.png">
<img width="1474" alt="Screenshot 2021-03-02 at 3 18 26 PM" src="https://user-images.githubusercontent.com/53594676/109630107-8ac75080-7b6a-11eb-9ff2-a78bd3af8561.png">
