### ISSUE TITLE
Timeline graph only works if it is the first/only graph on a page.

### ISSUE THREAD

**Issue by TemperedSolver** [cerner/terra-graphs#84]
# Bug Report

## Description
At two points (lines 206, 210) the Carbon timeline graph uses getElementByClassName on the entire document object to retrieve elements using generic class names shared by all of the graphs. This results in the wrong elements being used for size calculations if other graphs are on the page.

### Graphs affected

* [ ]  Bar graph
* [ ]  Bubble graph
* [ ]  Gantt chart
* [ ]  Line graph
* [ ]  Paired result
* [ ]  Pie chart
* [ ]  Scatter plot
* [x]  Timeline

## Steps to Reproduce

1. Put a Gantt chart before a Timeline on the same page.
2.
3.
4.

## Link to CodeSandbox
Use [this](https://codesandbox.io/s/keen-thunder-nh5gk?file=/src/data.js) template to reproduce the behavior.

## Expected Behavior
The size calculations are done from attributes of the correct graph.

## Possible Solution
Replace the timeline's logic with the logic used by all the other graphs, using the graphContainer instead of the DOM to handle these calculations. Alternatively, for a quick and dirty fix that leaves the timeline graph with its unique behavior, add an intermediate ID selector using the graph ID passed into the constructor on the initial JSON configuration.
-  e.g. document.getElementById(config.bindTo).getElementsByClassName("tick")

## Environment
Carbon Graphs 2.16.0

**Comment by AshishMotanamGurunadham** [comment]
@TemperedSolver This issue fix is out for [review](https://github.com/cerner/terra-graphs/pull/91). Meanwhile can you please please verify these changes with your code.
