### ISSUE TITLE
Y-axis icons and y2-axis icons not updating during reflow

### ISSUE THREAD

**Issue by NarasimhaShenoi** [cerner/terra-graphs#87]
# Bug Report

## Description

Y-axis icons and y2-axis icons not updating based on the values passed down to the reflow. If there is no data for a particular legend, the y-axis icon should hide and if there is data for a particular legend during panning, y-axis icons should display.

## Link to CodeSandbox
Use [this](https://codesandbox.io/s/ecstatic-heisenberg-5tugf?file=/src/data.js) template to reproduce the behavior.

## Expected Behavior

If there is no data for a particular legend during panning, the y-axis icons should hide and if there is data for a particular legend during panning, the y-axis icon should display. Same should happen for y2 as well.

**Comment by NarasimhaShenoi** [comment]
@ryanthemanuel  @mraplumb  @sdadn Can you please provide an ETA for this issue?

**Comment by AshishMotanamGurunadham** [comment]
@NarasimhaShenoi if everything goes as expected it will be out for review by the end of this week or by the start of next week.

**Comment by AshishMotanamGurunadham** [comment]
@NarasimhaShenoi We fixed this issue and it is out for [review](https://github.com/cerner/terra-graphs/pull/94/files). Meanwhile, you can test this in your application by pulling in the [branch](https://github.com/cerner/terra-graphs/tree/fix-issue-87) changes.
