### ISSUE TITLE
Graph does not load properly, when there is lazy loading component

### ISSUE THREAD

**Issue by SharathAlur** [cerner/terra-graphs#89]
# Bug Report

## Description

The graph does not load properly when there is a lazy loading component on the dom along with the carbon-graph.

### Graphs affected

* [ ]  Bar graph
* [ ]  Bubble graph
* [ ]  Gantt chart
* [x]  Line graph
* [ ]  Paired result
* [ ]  Pie chart
* [ ]  Scatter plot
* [ ]  Timeline

## Steps to Reproduce

1. Add a component and import it using React.lazy()

## Additional Context / Screenshots

<img width="1680" alt="lazy loading issue" src="https://user-images.githubusercontent.com/22268936/113819896-96282000-9797-11eb-99e6-2a2c68a87ac0.png">

## Expected Behavior

The graph should load properly.

## Possible Solution

I had posted the same in teams channel. Here is the [link](https://teams.microsoft.com/l/message/19:ae0d6e7035e041c7b3fa1a1b9ad27c2d@thread.skype/1617010416621?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1617010416621&teamName=Terra&channelName=Carbon%20Graphs&createdTime=1617010416621).

**Comment by mraplumb** [comment]
@SharathAlur can you provide a URL or some basic steps of how to load this in a browser where we can see the issue and review what is happening?

**Comment by SharathAlur** [comment]
@mraplumb Unfortunately I could not reproduce in the codesandbox. I am not sure if it is fine to provide the internal github link. All the details are mentioned in the teams channel.
https://teams.microsoft.com/l/message/19:ae0d6e7035e041c7b3fa1a1b9ad27c2d@thread.skype/1617010416621?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1617010416621&teamName=Terra&channelName=Carbon%20Graphs&createdTime=1617010416621

**Comment by SharathAlur** [comment]
The issue is resolved once I wrapped the lazy loading component with React.Suspense.

**Comment by ryanthemanuel** [comment]
Good to hear @SharathAlur.  Closing this as a non issue then.
